ci: Add an integration test in the CI/CD (#3)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Build and Release
+name: Test, Build and Release
 
 on:
   push:
@@ -29,6 +29,17 @@ jobs:
 
     - name: Run tests
       run: go test -v ./...
+
+    - name: Integration tests
+      run: |
+        go build -o rolenv
+        ./rolenv run --config testdata/rolenv.env
+        sleep 5
+        if docker ps | grep rolenv-test-cont; then
+          echo "The container Rolenv is running"
+        else
+          echo "Error, the container is not running" && exit 1
+        fi
 
   build:
     needs: test
